name: build.yml
on:
  workflow_dispatch: {}
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses:  actions/checkout@v4
    - name: build
      uses: game-ci/unity-builder@v4.3
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneOSX
        unityVersion: 6000.0.36f1
        
    - name: Upload the WebGL Build
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: build
  
